### ISSUE TITLE
arreglar funciones get en database

### ISSUE THREAD

**Issue by gaston1709** [ffpp2003/SAPEICore#33]
en la funcion getcorregir numero de columas y tipo de int a int64 donde corresponda (id)

**Comment by Corte0** [comment]
Sigue roto, pero ahora solo la parte que es por nombre. copipasteando el bucle donde se obtienen los datos de getbyid todo anda, pero me parece que no tiene sentido, habria que crear una funcion auxuliar, o ver la forma de como hace para no repetir tanto codigo
